Newmmrdiversify
meta-soul/MetaSpore pull request #48
Opened 2022-04-12 07:15 UTC by Liusy12138

1、delete idea
2、revise issue

2022-04-13 02:55 UTC, intelligencegear requested changes

2022-04-13 02:55 UTC, intelligencegear commented on demo/movielens/online/src/main/java/com/dmetasoul/metaspore/demo/movielens/abtesting/experiment/diversify/MMRDiversifyExperiment.java
> +
delete this blank line

2022-04-13 02:55 UTC, intelligencegear commented on demo/movielens/online/src/main/java/com/dmetasoul/metaspore/demo/movielens/diversify/diversifier/impl/MaximalMarginalRelevanceDiversifier.java
> +    public static final String DIVERSIFIER_NAME = "MaximalMarginalRelevanceDiversifier";
ALGO_NAME or DIVERSIFIER_NAME?

2022-04-13 02:55 UTC, intelligencegear commented on demo/movielens/online/src/main/java/com/dmetasoul/metaspore/demo/movielens/diversify/diversifier/impl/MaximalMarginalRelevanceDiversifier.java
> +    public static final double LAMBDA = 0.7;
please rename to default_lambda or something else.

2022-04-13 02:55 UTC, intelligencegear commented on demo/movielens/online/src/main/java/com/dmetasoul/metaspore/demo/movielens/diversify/diversifier/impl/MaximalMarginalRelevanceDiversifier.java
> +    // simScore={A\cup B}/{A\cup B}
please change this to simScore=\frac{A \cup B}/{A \cup B}

2022-04-13 02:55 UTC, intelligencegear commented on demo/movielens/online/src/main/java/com/dmetasoul/metaspore/demo/movielens/diversify/diversifier/impl/SimpleDiversifier.java
ALGO_NAME or DIVERSIFIER_NAME?

2022-04-13 02:55 UTC, intelligencegear commented on demo/movielens/online/src/main/java/com/dmetasoul/metaspore/demo/movielens/diversify/diversifier/impl/SimpleDiversifier.java
> +    public static Map<String, Integer> groupByType(List<ItemModel> numbers) {
please do not write this function twice, move this into some utils class or parent class.

2022-04-13 02:55 UTC, intelligencegear commented on demo/movielens/online/src/main/java/com/dmetasoul/metaspore/demo/movielens/diversify/impl/DiversifyServiceImpl.java
> +    public static final String DIVERSIFIER_NAMES = "SimpleDiversifier";
Diversifier_NAME(S)? or something else name?

2022-04-13 02:55 UTC, intelligencegear commented on demo/movielens/online/src/main/java/com/dmetasoul/metaspore/demo/movielens/diversify/diversifier/DiverseProvider.java
> +        return diversifierMap.get(name.toLowerCase());
why delete 
`public Collection<Diversifier> getDiversifiers(Collection<String> names)`
this function?

2022-04-13 02:55 UTC, intelligencegear commented on demo/movielens/online/src/main/java/com/dmetasoul/metaspore/demo/movielens/diversify/diversifier/impl/MaximalMarginalRelevanceDiversifier.java
> +// * https://dl.acm.org/doi/10.1145/290941.291025
Give the paper name.

2022-04-13 03:07 UTC, intelligencegear reviewed
please add this check.

2022-04-13 03:07 UTC, intelligencegear commented on demo/movielens/online/src/main/java/com/dmetasoul/metaspore/demo/movielens/model/ItemModel.java
> +    public void setGenreList(String genre) {
if (StringUtils.isEmpty(genre)) {return ...}

2022-04-13 06:17 UTC, intelligencegear requested changes

2022-04-13 06:17 UTC, intelligencegear commented on demo/movielens/online/src/main/java/com/dmetasoul/metaspore/demo/movielens/model/ItemModel.java
> +import static com.dmetasoul.metaspore.demo.movielens.common.Constants.SEQUENCE_FEATURE_SPLITTER;
remove this static import.

2022-04-13 06:17 UTC, intelligencegear commented on demo/movielens/online/src/main/java/com/dmetasoul/metaspore/demo/movielens/model/ItemModel.java
> +
remove this blank line.

2022-04-13 07:13 UTC, intelligencegear requested changes

2022-04-13 07:13 UTC, intelligencegear commented on demo/movielens/online/src/main/java/com/dmetasoul/metaspore/demo/movielens/model/ItemModel.java
> +import org.codehaus.plexus.util.StringUtils;
change this import to google guava or spring libraries.

2022-04-13 07:13 UTC, intelligencegear commented on demo/movielens/online/src/main/java/com/dmetasoul/metaspore/demo/movielens/retrieval/impl/RetrievalServiceImpl.java
> +
please revert this change.

2022-04-13 07:18 UTC, intelligencegear approved these changes
please change description of this squash commit.

2022-04-13 07:31 UTC, andafterall approved these changes

2022-04-15 06:18 UTC, intelligencegear approved these changes

2022-04-15 06:27 UTC, Liusy12138 commented
Associate `New mmrdiversify` with the `[demo] MaximalMarginalRelevanceDiversifier demo`

2022-04-15 06:37 UTC, merged